package com.aws.dynamodb.repositories.model;

import javax.xml.bind.annotation.XmlElement;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "FileTransferRequest")
public class FileTransferRequest {

	@XmlElement(nillable = true)
	private Integer requestId;
	private String fromBucket;
	private String s3Key;
	@XmlElement(nillable = true)
	private String status;

	public FileTransferRequest() {
	}

	public FileTransferRequest(String fromBucket, String s3Key) {
		this.fromBucket = fromBucket;
		this.s3Key = s3Key;
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	public Integer getRequestId() {
		return requestId;
	}

	public void setRequestId(Integer requestId) {
		this.requestId = requestId;
	}

	@DynamoDBAttribute
	public String getFromBucket() {
		return fromBucket;
	}

	public void setFromBucket(String fromBucket) {
		this.fromBucket = fromBucket;
	}

	@DynamoDBAttribute
	public String getS3Key() {
		return s3Key;
	}

	public void setS3Key(String s3Key) {
		this.s3Key = s3Key;
	}

	@DynamoDBAttribute
	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
}
